### ISSUE TITLE
About GPUs and training time

### ISSUE THREAD

**Issue by eine-kenta** [yangyangyang127/PointCLIP_V2#2]
Hi, I am very interested in your research.

Could you tell me what GPUs you used and how long the training took?

**Comment by yangyangyang127** [comment]
Dear eine-kenta,

We use one NVIDIA RTX A6000 GPU with 48G memory. But the code only consumes <10G memory.

We provide the code of the zero-shot classification and segmentation task, and no training time is needed.

Xiangyang Zhu
